name: promote pipeline

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: bridgecrewio/checkov-action@v12
        with:
          framework: dockerfile
          dockerfile_path: Dockerfile
          check: CKV_DOCKER_1,CKV_DOCKER_7,CKV_DOCKER_8
      - id: get-tag
        run: echo "TAG=$(git tag --points-at HEAD)" >> "$GITHUB_OUTPUT"

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.API_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.actor }}/poc-devsecops:${{ steps.get-tag.outputs.TAG }}
