name: vulnerability scan

on:
  push: {}

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.API_TOKEN }}

      - run: |
          #!/bin/sh

          set -xe

          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

          trivy image --format cyclonedx --output cyclonedx-report.json ghcr.io/warapong-pj/poc-devsecops:323575b88632309437bc4f7d59dcb6844a0df22b

          cat cyclonedx-report.json

  dast:
    runs-on: ubuntu-latest

    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.API_TOKEN }}
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - run: |
          #!/bin/sh

          set -xe

          docker run -i -t -d -p 8000:8000 --name poc-devsecops ghcr.io/warapong-pj/poc-devsecops:323575b88632309437bc4f7d59dcb6844a0df22b

          curl -L -O https://github.com/projectdiscovery/nuclei/releases/download/v3.4.10/nuclei_3.4.10_linux_amd64.zip
          unzip nuclei_3.4.10_linux_amd64.zip
          mv nuclei /usr/local/bin/
          rm -rf *

          nuclei -target "http://localhost:8000" -sarif-export dast-report.sarif
          cat dast-report.sarif

          docker stop poc-devsecops
          docker rm poc-devsecops
