name: vulnerability scan

on:
  push: {}

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.API_TOKEN }}

      - run: |
          #!/bin/sh

          set -xe

          git clone https://github.com/CycloneDX/Sunshine.git
          cd Sunshine
          pip install -r requirements.txt

          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

          trivy image --format cyclonedx --output cyclonedx-result.json ghcr.io/warapong-pj/poc-devsecops:323575b88632309437bc4f7d59dcb6844a0df22b

          python sunshine.py -i cyclonedx-result.json -o cyclonedx-report.html
          cat cyclonedx-report.html
